### ISSUE TITLE
Cute badges from IMVU

### ISSUE THREAD

**Issue by Majora-Joestar** [Smumbo/DefinitiveIcons#3]
Hi ! There is a lot of amazing badges on IMVU, but I have no idea how, or even if, it would be possible to add them as 3ds badges. Hopefully, it might !
https://badgedirectory.com/in-canvas/kelie/128

Thank you !

**Comment by Smumbo** [comment]
Hi, this GitHub repo is a page for suggestions to add to my badge set. For general information about custom badges on 3DS, I would recommend looking it up on Reddit or GBATemp.

In order to add custom badges to 3DS, you just have to download them and ensure that they fit in PNGs with dimensions in multiples of 64x64, then add them to your system using [GYTB](https://github.com/MrCheeze/GYTB).
