### ISSUE TITLE
NES logo

### ISSUE THREAD

**Issue by donavinphelps** [Smumbo/DefinitiveIcons#6]
Please add the official NES logo

Here is an image sample: https://commons.wikimedia.org/wiki/File:NES_logo.svg

Thank you!

**Comment by Smumbo** [comment]
Hi, sorry for not getting around to this sooner. I originally decided not to include this specific logo for NES, as it's nearly illegible at the size the badges export to. But since you requested it, I've added it in [v3.1](https://github.com/Smumbo/DefinitiveIcons/releases/tag/v3.1).

I'll also include it here for your convenience:
![System  Nintendo Entertainment System 3](https://github.com/user-attachments/assets/70d2a290-1527-4da3-baae-6334b2e381ed)
